In [1]:
import pandas as pd
import numpy as np

In [30]:
df0=pd.read_excel("compte partis/file2015.ods")

C:\Users\math\AppData\Local\Temp\ipykernel_1152\2371227319.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  column[3+i]=df0.iloc[0][3+i].strip().lower()

,Nom parti,immobilisations incorporelles,ecart d'acquisition,immobilisations corporelles :,- terrains et constructions,- autres immobilisations corporelles,immobilisations financières :,participations,- prêts,- autres immobilisations financières,...,produits d’exploitation,-dont facturation des services rendus aux candidats pour les campagnes électorales,autres produits,produits financiers,produits exceptionnels,reprise sur provisions et amortissements,- reprise sur provisions pour campagnes électorales :,total des produits,résultat d'ensemble (perte),total
0,DÉMOCRATIE ET RÉPUBLIQUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,651,NaN,NaN,NaN,199410,25590,225000
1,L'ALLIANCE RÉGIONALE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10,30,NaN,NaN,47807,1001,48808
2,CENTRE NATIONAL DES INDÉPENDANTS ET PAYSANS,NaN,NaN,NaN,55256,2529,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83,NaN,2877,NaN,70552,7318,77870
3,FRONT NATIONAL,14290,NaN,534026,59760,NaN,NaN,14000,3976772,152017,...,121280,NaN,1562620,211610,37369,54859,NaN,11062955,2905453,13968408
4,GÉNÉRATION ÉCOLOGIE - LES BLEUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,44,NaN,NaN,NaN,21200,8999,30199

In [4]:
df=pd.read_excel("compte partis/file2021.xlsx")

In [5]:
df.columns=df.iloc[1]
df.drop(index=[0,1],inplace=True)
df.drop(columns=["N°","Unité monétaire"],inplace=True)

In [58]:
for i in df.columns:
    print(i)

Nom du parti
Exercice
Écarts d'acquisition (brut)
Écarts d'acquisition (amortissements et dépréciations)
Écarts d'acquisition (net)
Immobilisations incorporelles (brut)
Immobilisations incorporelles (amortissements et dépréciations)
Immobilisations incorporelles (net)
Terrains et constructions (brut)
Terrains et constructions (amortissements et dépréciations)
Terrains et constructions (net)
Autres immobilisations corporelles (brut)
Autres immobilisations corporelles (amortissements et dépréciations)
Autres immobilisations corporelles (net)
Participations et créances rattachées (brut)
Participations et créances rattachées (amortissements et dépréciations)
Participations et créances rattachées (net)
Autres titres immobilisés (brut)
Autres titres immobilisés (amortissements et dépréciations)
Autres titres immobilisés (net)
Prêts à des partis ou groupements politiques (brut)
Prêts à des partis ou groupements politiques (amortissements et dépréciations)
Prêts à des partis ou groupements politiques (net)
Prêts aux candidats (brut)
Prêts aux candidats (amortissements et dépréciations)
Prêts aux candidats (net)
Prêts aux organisations territoriales ou spécialisées du parti (brut)
Prêts aux organisations territoriales ou spécialisées du parti (amortissements et dépréciations)
Prêts aux organisations territoriales ou spécialisées du parti (net)
Prêts à d'autres organismes (brut)
Prêts à d'autres organismes (amortissements et dépréciations)
Prêts à d'autres organismes (net)
Autres prêts (brut)
Autres prêts (amortissements et dépréciations)
Autres prêts (net)
Autres immobilisations financières (brut)
Autres immobilisations financières (amortissements et dépréciations)
Autres immobilisations financières (net)
Total I (brut)
Total I (amortissements et dépréciations)
Total I (net)
Stocks et en-cours (brut)
Stocks et en-cours (amortissements et dépréciations)
Stocks et en-cours (net)
Avances et acomptes versés sur commande (brut)
Avances et acomptes versés sur commande (amortissements et dépréciations)
Avances et acomptes versés sur commande (net)
Créances clients et comptes rattachés (brut)
Créances clients et comptes rattachés (amortissements et dépréciations)
Créances clients et comptes rattachés (net)
Créances auprès de partis ou groupements politiques (brut)
Créances auprès de partis ou groupements politiques (amortissements et dépréciations)
Créances auprès de partis ou groupements politiques (net)
Autres créances (brut)
Autres créances (amortissements et dépréciations)
Autres créances (net)
Valeurs mobilières de placement (brut)
Valeurs mobilières de placement (amortissements et dépréciations)
Valeurs mobilières de placement (net)
Disponibilités (brut)
Disponibilités (amortissements et dépréciations)
Disponibilités (net)
Charges constatées d'avance (brut)
Charges constatées d'avance (amortissements et dépréciations)
Charges constatées d'avance (net)
Total II (brut)
Total II (amortissements et dépréciations)
Total II (net)
Actifs des entités non significatives (III) (brut)
Actifs des entités non significatives (III) (amortissements et dépréciations)
Actifs des entités non significatives (III) (net)
TOTAL GÉNÉRAL (I + II + III) (brut)
TOTAL GÉNÉRAL (I + II + III) (amortissements et dépréciations)
TOTAL GÉNÉRAL (I + II + III) (net)
Réserves
Réserves pour frais de campagnes électorales
Réserves pour frais de manifestation
Report à nouveau
Excédent ou déficit de l'exercice
Autres fonds propres
Intérêt des tiers
Total I
Provisions pour risques
Provisions pour charges
Total II
Emprunts et dettes auprès d'établissement de crédit
Emprunts et dettes auprès de personnes physiques à taux préférentiel
Autres emprunts et dettes auprès de personnes physiques
Emprunts et dettes auprès de partis ou groupements politiques
Dettes fournisseurs et comptes rattachés
Dettes fiscales et sociales
Dettes envers les candidats
Dettes envers les organisations territoriales et spécialisées
Autres dettes
Produits constatés d'avance
Total III
Passifs des entités non significatives (IV)
TOTAL GÉNÉRAL (I + II + III + IV)
Cotisations des adhérents
Cotisations des élus
Aide publique 1ère fraction
Aide publique 2nde fraction
Autres aides publiques
Dons de personne physique
Dévolutions de l'excédent des comptes de campagne
Dévolutions de partis ou groupements politiques
Contributions financières de partis ou groupements politiques
Prestations de services (manifestations et colloques)
Prestations de services aux candidats
Reprise sur amortissements, dépréciations, provisions et transferts de charges
Ventes de marchandises, productions vendue (biens et services), production stockée et production immobilisée
Produits des entités non significatives
Autres produits
Total I
Contributions versées aux candidats
Prises en charge de dépenses électorales
Contributions à des partis ou groupements politiques
Contributions à des organisations territoriales ou spécialisées du parti
Contributions à d'autres organismes
Achats de marchandises et variation de stocks
Congrès, manifestation et université
Communication (presse, publications, télévisions, publicité, sites internet, réseaux sociaux)
Locations, redevances de crédit-bail et charges locatives
Déplacements, missions et réceptions
Honoraires
Personnels extérieurs
Autres achats et autres charges externes
Impôts et taxes
Salaires et traitements
Charges sociales
Dotations aux amortissements et dépréciations sur immobilisations
Dotations aux dépréciations sur actif circulant
Dotations aux provisions
Charges des entités non significatives
Autres charges
Total II
1. RÉSULTAT DES ACTIVITÉS (I - II)
Produits de participation
Produits des autres immobilisations financières
Autres intérêts et produits assimilés
Reprises sur provisions, dépréciations et transferts de charge fin.
Produits nets sur cessions de valeurs mobilières de placement
Total III
Dotations aux amortissements, aux dépréciations et aux provisions fin.
Intérêts et charges assimilées
Charges nettes sur cessions de valeurs mobilières de placement
Total IV
2. RÉSULTAT FINANCIER (III - IV)
3. RÉSULTAT COURANT (I - II + III - IV)
PE sur opérations de gestion
PE sur opérations en capital
Reprise sur provisions, dépréciations et transferts de charges excep.
Total V
CE sur opérations de gestion
CE sur opérations en capital
Dotations aux amortissements, aux dépréciations et aux provisions excep.
Total VI
4. RÉSULTAT EXCEPTIONNEL (V - VI)
Impôts sur les bénéfices (VII)
Dotations aux amortissements des écarts d'acquisition (VIII)
Intérêts des tiers (IX)
Total des produits (I + III + V)
Total des charges (II + IV +VI + VII + VIII + IX)
EXCÉDENT OU DÉFICIT D'ENSEMBLE

In [52]:
df.head()

1,Nom du parti,Exercice,Écarts d'acquisition (brut),Écarts d'acquisition (amortissements et dépréciations),Écarts d'acquisition (net),Immobilisations incorporelles (brut),Immobilisations incorporelles (amortissements et dépréciations),Immobilisations incorporelles (net),Terrains et constructions (brut),Terrains et constructions (amortissements et dépréciations),...,CE sur opérations en capital,"Dotations aux amortissements, aux dépréciations et aux provisions excep.",Total VI,4. RÉSULTAT EXCEPTIONNEL (V - VI),Impôts sur les bénéfices (VII),Dotations aux amortissements des écarts d'acquisition (VIII),Intérêts des tiers (IX),Total des produits (I + III + V),Total des charges (II + IV +VI + VII + VIII + IX),EXCÉDENT OU DÉFICIT D'ENSEMBLE
2,L'ALLIANCE RÉGIONALE,2021,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,17508,22430,-4922
3,CENTRE NATIONAL DES INDÉPENDANTS ET PAYSANS,2021,0,0,0,0,0,0,198184,183184,...,0,0,9061,-3924,0,0,0,123677,89229,34448
4,RASSEMBLEMENT NATIONAL,2021,0,0,0,44591,44591,0,91469,31709,...,11223,1941599,2983234,-2706172,0,0,0,9553471,12325387,-2771917
5,GÉNÉRATION ÉCOLOGIE,2021,0,0,0,5139,1789.2,3349.8,0,0,...,0,0,0,0,0,0,0,275507.18,223430.43,52076.75
6,GROUPEMENT FRANCE-RÉUNION,2021,0,0,0,179,179,0,0,0,...,0,0,0,0,0,0,0,60334,18363,41972

In [42]:
df.iloc[1]

Unnamed: 0                                                         N°
Unnamed: 1                                               Nom du parti
Unnamed: 2                                            Unité monétaire
Unnamed: 3                                                   Exercice
ACTIF IMMOBILISÉ                          Écarts d'acquisition (brut)
                                          ...
Unnamed: 161        Dotations aux amortissements des écarts d'acqu...
Unnamed: 162                                  Intérêts des tiers (IX)
Unnamed: 163                         Total des produits (I + III + V)
Unnamed: 164        Total des charges (II + IV +VI + VII + VIII + IX)
Unnamed: 165                           EXCÉDENT OU DÉFICIT D'ENSEMBLE
Name: 1, Length: 166, dtype: object

In [41]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'ACTIF IMMOBILISÉ', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 156', 'Unnamed: 157', 'Unnamed: 158', 'Unnamed: 159',
       'Unnamed: 160', 'Unnamed: 161', 'Unnamed: 162', 'Unnamed: 163',
       'Unnamed: 164', 'Unnamed: 165'],
      dtype='object', length=166)

In [3]:
column=list(df.columns)
for i in range(len(column[3:])):
    column[3+i]=df.iloc[1][3+i].strip().lower()
df.columns=column
df.drop(0,inplace=True)
df.reset_index(inplace=True)
df.drop(columns=["index"],inplace=True)
df.drop(index=list(df[df["Unité monétaire"]!='EUR'].index),inplace=True)
df.head()
df.drop(columns=["Unité monétaire","Num parti "],inplace=True)
df.head()

C:\Users\math\AppData\Local\Temp\ipykernel_4056\113524677.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  column[3+i]=df.iloc[1][3+i].strip().lower()

KeyError: 'Unité monétaire'

In [47]:
np.isnan(df.describe()["ecart d'acquisition"]["top"])

True

In [25]:
new_col=list(df.columns)
for i in range(len(new_col)):
    if new_col[i]=='total':
        new_col[i]='total0'
        break
df.columns=new_col

In [ ]:
data=df.describe()
void=[]
for i in df.columns:
    if data[i][]

In [35]:
df.describe()

,Nom parti,immobilisations incorporelles,ecart d'acquisition,immobilisations corporelles :,- terrains et constructions,- autres immobilisations corporelles,immobilisations financières :,participations,- prêts,- autres immobilisations financières,...,produits d’exploitation,-dont facturation des services rendus aux candidats pour les campagnes électorales,autres produits,produits financiers,produits exceptionnels,reprise sur provisions et amortissements,- reprise sur provisions pour campagnes électorales :,total des produits,résultat d'ensemble (perte),total
count,336,36,0,5,19,101,2,21,35,96,...,57,13,89,99,59,20,3,336,336,336
unique,336,36,0,5,19,101,2,17,33,91,...,57,13,84,88,57,20,3,313,149,330
top,DÉMOCRATIE ET RÉPUBLIQUE,14290,NaN,534026,55256,2529,1050,15,12000,30,...,121280,1267590,50,2,150,2877,148300,0,0,0
freq,1,1,NaN,1,1,1,1,4,2,4,...,1,1,3,4,2,1,1,19,187,6

In [42]:
df.head()

,Num parti,Nom parti,Unité monétaire,Immobilisations incorporelles,Ecart d'acquisition,Immobilisations corporelles :,- terrains et constructions,- autres immobilisations corporelles,Immobilisations financières :,participations,...,Produits d’exploitation,-dont facturation des services rendus aux candidats pour les campagnes électorales,Autres produits,Produits financiers,Produits exceptionnels,Reprise sur provisions et amortissements,- reprise sur provisions pour campagnes électorales :,Total des produits,Résultat d'ensemble (perte),Total
0,1,DÉMOCRATIE ET RÉPUBLIQUE,euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,651,NaN,NaN,NaN,199410,25590,225000
1,5,L'ALLIANCE RÉGIONALE,euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10,30,NaN,NaN,47807,1001,48808
2,13,CENTRE NATIONAL DES INDÉPENDANTS ET PAYSANS,euro,NaN,NaN,NaN,55256,2529,NaN,NaN,...,NaN,NaN,NaN,83,NaN,2877,NaN,70552,7318,77870
3,40,FRONT NATIONAL,euro,14290,NaN,534026,59760,NaN,NaN,14000,...,121280,NaN,1562620,211610,37369,54859,NaN,11062955,2905453,13968408
4,42,GÉNÉRATION ÉCOLOGIE - LES BLEUS,euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,44,NaN,NaN,NaN,21200,8999,30199

In [9]:
df=pd.read_excel("compte partis/file2011.xlsx")

In [10]:
df.head()

,Num parti,Nom parti,Unité monétaire,I. - Actif immobilisé,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80
0,(chiffres),litttéral,NaN,Immobilisations incorporelles,Ecart d'acquisition,Immobilisations corporelles :,- terrains et constructions,- autres immobilisations corporelles,Immobilisations financières :,participations,...,Produits d’exploitation,-dont facturation des services rendus aux cand...,Autres produits,Produits financiers,Produits exceptionnels,Reprise sur provisions et amortissements,- reprise sur provisions pour campagnes électo...,Total des produits,Résultat d'ensemble (perte),Total
1,1,DÉMOCRATIE ET RÉPUBLIQUE,euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,871,NaN,NaN,NaN,629308,0,629308
2,5,L'ALLIANCE RÉGIONALE,euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34467,4157,38624
3,13,CENTRE NATIONAL DES INDÉPENDANTS ET PAYSANS,euro,NaN,NaN,NaN,94893,6820,NaN,NaN,...,NaN,NaN,NaN,1223,NaN,10674,NaN,154878,12501,167379
4,40,FRONT NATIONAL,euro,122,NaN,NaN,59760,458555,NaN,14000,...,82416,NaN,385691,28097,5538435,1334093,NaN,11865179,0,11865179

In [24]:
len(df.columns)

79

In [25]:
len(df0.columns)

80

In [13]:
a="""Nom du parti
    Exercice
    Écarts d'acquisition (net)
    Immobilisations incorporelles (net)
    Terrains et constructions (net)
    Autres immobilisations corporelles (net)
    Participations et créances rattachées (net)
    Autres titres immobilisés (net)
    Prêts à des partis ou groupements politiques (net)
    Prêts aux candidats (net)
    Prêts aux organisations territoriales ou spécialisées du parti (net)
    Prêts à d'autres organismes (net)
    Autres prêts (net)
    Autres immobilisations financières (net)
    Total I (net)
    Stocks et en-cours (net)
    Avances et acomptes versés sur commande (net)
    Créances clients et comptes rattachés (net)
    Créances auprès de partis ou groupements politiques (net)
    Autres créances (net)
    Valeurs mobilières de placement (net)
    Disponibilités (net)
    Charges constatées d'avance (net)
    Total II (net)
    Actifs des entités non significatives (III) (net)
    TOTAL GÉNÉRAL (I + II + III) (net)
    Réserves
    Réserves pour frais de campagnes électorales
    Réserves pour frais de manifestation
    Report à nouveau
    Excédent ou déficit de l'exercice
    Autres fonds propres
    Intérêt des tiers
    Total I
    Provisions pour risques
    Provisions pour charges
    Total II
    Emprunts et dettes auprès d'établissement de crédit
    Emprunts et dettes auprès de personnes physiques à taux préférentiel
    Autres emprunts et dettes auprès de personnes physiques
    Emprunts et dettes auprès de partis ou groupements politiques
    Dettes fournisseurs et comptes rattachés
    Dettes fiscales et sociales
    Dettes envers les candidats
    Dettes envers les organisations territoriales et spécialisées
    Autres dettes
    Produits constatés d'avance
    Total III
    Passifs des entités non significatives (IV)
    TOTAL GÉNÉRAL (I + II + III + IV)
    Cotisations des adhérents
    Cotisations des élus
    Aide publique 1ère fraction
    Aide publique 2nde fraction
    Autres aides publiques
    Dons de personne physique
    Dévolutions de l'excédent des comptes de campagne
    Dévolutions de partis ou groupements politiques
    Contributions financières de partis ou groupements politiques
    Prestations de services (manifestations et colloques)
    Prestations de services aux candidats
    Reprise sur amortissements, dépréciations, provisions et transferts de charges
    Ventes de marchandises, productions vendue (biens et services), production stockée et production immobilisée
    Produits des entités non significatives
    Autres produits
    Total I
    Contributions versées aux candidats
    Prises en charge de dépenses électorales
    Contributions à des partis ou groupements politiques
    Contributions à des organisations territoriales ou spécialisées du parti
    Contributions à d'autres organismes
    Achats de marchandises et variation de stocks
    Congrès, manifestation et université
    Communication (presse, publications, télévisions, publicité, sites internet, réseaux sociaux)
    Locations, redevances de crédit-bail et charges locatives
    Déplacements, missions et réceptions
    Honoraires
    Personnels extérieurs
    Autres achats et autres charges externes
    Impôts et taxes
    Salaires et traitements
    Charges sociales
    Dotations aux amortissements et dépréciations sur immobilisations
    Dotations aux dépréciations sur actif circulant
    Dotations aux provisions
    Charges des entités non significatives
    Autres charges
    Total II
        RÉSULTAT DES ACTIVITÉS (I - II)
    Produits de participation
    Produits des autres immobilisations financières
    Autres intérêts et produits assimilés
    Reprises sur provisions, dépréciations et transferts de charge fin.
    Produits nets sur cessions de valeurs mobilières de placement
    Total III
    Dotations aux amortissements, aux dépréciations et aux provisions fin.
    Intérêts et charges assimilées
    Charges nettes sur cessions de valeurs mobilières de placement
    Total IV
        RÉSULTAT FINANCIER (III - IV)
        RÉSULTAT COURANT (I - II + III - IV)
    PE sur opérations de gestion
    PE sur opérations en capital
    Reprise sur provisions, dépréciations et transferts de charges excep.
    Total V
    CE sur opérations de gestion
    CE sur opérations en capital
    Dotations aux amortissements, aux dépréciations et aux provisions excep.
    Total VI
        RÉSULTAT EXCEPTIONNEL (V - VI)
    Impôts sur les bénéfices (VII)
    Dotations aux amortissements des écarts d'acquisition (VIII)
    Intérêts des tiers (IX)
    Total des produits (I + III + V)
    Total des charges (II + IV + VI + VII + VIII + IX)
    EXCÉDENT OU DÉFICIT D'ENSEMBLE
"""

In [9]:
b=a.split("\n")

In [12]:
for i in b:
    print(i.strip())

Nom du parti
Exercice
Écarts d'acquisition (net)
Immobilisations incorporelles (net)
Terrains et constructions (net)
Autres immobilisations corporelles (net)
Participations et créances rattachées (net)
Autres titres immobilisés (net)
Prêts à des partis ou groupements politiques (net)
Prêts aux candidats (net)
Prêts aux organisations territoriales ou spécialisées du parti (net)
Prêts à d'autres organismes (net)
Autres prêts (net)
Autres immobilisations financières (net)
Total I (net)
Stocks et en-cours (net)
Avances et acomptes versés sur commande (net)
Créances clients et comptes rattachés (net)
Créances auprès de partis ou groupements politiques (net)
Autres créances (net)
Valeurs mobilières de placement (net)
Disponibilités (net)
Charges constatées d'avance (net)
Total II (net)
Actifs des entités non significatives (III) (net)
TOTAL GÉNÉRAL (I + II + III) (net)
Réserves
Réserves pour frais de campagnes électorales
Réserves pour frais de manifestation
Report à nouveau
Excédent ou déficit de l'exercice
Autres fonds propres
Intérêt des tiers
Total I
Provisions pour risques
Provisions pour charges
Total II
Emprunts et dettes auprès d'établissement de crédit
Emprunts et dettes auprès de personnes physiques à taux préférentiel
Autres emprunts et dettes auprès de personnes physiques
Emprunts et dettes auprès de partis ou groupements politiques
Dettes fournisseurs et comptes rattachés
Dettes fiscales et sociales
Dettes envers les candidats
Dettes envers les organisations territoriales et spécialisées
Autres dettes
Produits constatés d'avance
Total III
Passifs des entités non significatives (IV)
TOTAL GÉNÉRAL (I + II + III + IV)
Cotisations des adhérents
Cotisations des élus
Aide publique 1ère fraction
Aide publique 2nde fraction
Autres aides publiques
Dons de personne physique
Dévolutions de l'excédent des comptes de campagne
Dévolutions de partis ou groupements politiques
Contributions financières de partis ou groupements politiques
Prestations de services (manifestations et colloques)
Prestations de services aux candidats
Reprise sur amortissements, dépréciations, provisions et transferts de charges
Ventes de marchandises, productions vendue (biens et services), production stockée et production immobilisée
Produits des entités non significatives
Autres produits
Total I
Contributions versées aux candidats
Prises en charge de dépenses électorales
Contributions à des partis ou groupements politiques
Contributions à des organisations territoriales ou spécialisées du parti
Contributions à d'autres organismes
Achats de marchandises et variation de stocks
Congrès, manifestation et université
Communication (presse, publications, télévisions, publicité, sites internet, réseaux sociaux)
Locations, redevances de crédit-bail et charges locatives
Déplacements, missions et réceptions
Honoraires
Personnels extérieurs
Autres achats et autres charges externes
Impôts et taxes
Salaires et traitements
Charges sociales
Dotations aux amortissements et dépréciations sur immobilisations
Dotations aux dépréciations sur actif circulant
Dotations aux provisions
Charges des entités non significatives
Autres charges
Total II
RÉSULTAT DES ACTIVITÉS (I - II)
Produits de participation
Produits des autres immobilisations financières
Autres intérêts et produits assimilés
Reprises sur provisions, dépréciations et transferts de charge fin.
Produits nets sur cessions de valeurs mobilières de placement
Total III
Dotations aux amortissements, aux dépréciations et aux provisions fin.
Intérêts et charges assimilées
Charges nettes sur cessions de valeurs mobilières de placement
Total IV
RÉSULTAT FINANCIER (III - IV)
RÉSULTAT COURANT (I - II + III - IV)
PE sur opérations de gestion
PE sur opérations en capital
Reprise sur provisions, dépréciations et transferts de charges excep.
Total V
CE sur opérations de gestion
CE sur opérations en capital
Dotations aux amortissements, aux dépréciations et aux provisions excep.
Total VI
RÉSULTAT EXCEPTIONNEL (V - VI)
Impôts sur les bénéfices (VII)
Dotations aux amortissements des écarts d'acquisition (VIII)
Intérêts des tiers (IX)
Total des produits (I + III + V)
Total des charges (II + IV + VI + VII + VIII + IX)
EXCÉDENT OU DÉFICIT D'ENSEMBLE