In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
a=pd.read_csv("deputes/deputes_2022.csv",delimiter=';')

,id,nom,nom_de_famille,prenom,sexe,date_naissance,lieu_naissance,num_deptmt,nom_circo,num_circo,...,anciens_mandats,profession,place_en_hemicycle,url_an,id_an,slug,url_nosdeputes,url_nosdeputes_api,nb_mandats,twitter
0,1,Thibault Bazin,Bazin,Thibault,H,1984-10-27,Nancy (Meurthe-et-Moselle),54,Meurthe-et-Moselle,4,...,22/06/2022 / 09/06/2024 / fin de législature|2...,Autre cadre (secteur privé),109,https://www2.assemblee-nationale.fr/deputes/fi...,642847,thibault-bazin,https://www.nosdeputes.fr/thibault-bazin,https://www.nosdeputes.fr/thibault-bazin/csv,0,thibault_bazin
1,2,Jean-Victor Castor,Castor,Jean-Victor,H,1962-04-21,Sinnamary (Guyane),973,Guyane,1,...,22/06/2022 / 09/06/2024 / fin de législature,Cadre technique d'entreprise,594,https://www2.assemblee-nationale.fr/deputes/fi...,795868,jean-victor-castor,https://www.nosdeputes.fr/jean-victor-castor,https://www.nosdeputes.fr/jean-victor-castor/csv,0,CASTORJeanVict1
2,3,Benoit Mournet,Mournet,Benoit,H,1986-01-16,Bagneres De Bigorre (Hautes-Pyrénées),65,Hautes-Pyrénées,2,...,22/06/2022 / 09/06/2024 / fin de législature,Cadre de la fonction publique,308,https://www2.assemblee-nationale.fr/deputes/fi...,794878,benoit-mournet,https://www.nosdeputes.fr/benoit-mournet,https://www.nosdeputes.fr/benoit-mournet/csv,0,BenoitMournet
3,4,Nicolas Meizonnet,Meizonnet,Nicolas,H,1983-12-22,Nimes (Gard),30,Gard,2,...,01/02/2020 / 21/06/2022 / fin de législature|2...,Ingénieur en informatique,33,https://www2.assemblee-nationale.fr/deputes/fi...,719436,nicolas-meizonnet,https://www.nosdeputes.fr/nicolas-meizonnet,https://www.nosdeputes.fr/nicolas-meizonnet/csv,0,NMeizonnet
4,5,Marc Fesneau,Fesneau,Marc,H,1971-01-11,Paris (Paris),41,Loir-et-Cher,1,...,22/06/2022 / 22/07/2022 / nomination comme mem...,Ministre,165,https://www2.assemblee-nationale.fr/deputes/fi...,719938,marc-fesneau,https://www.nosdeputes.fr/marc-fesneau,https://www.nosdeputes.fr/marc-fesneau/csv,0,MFesneau
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,615,Ingrid Dordain,Dordain,Ingrid,F,1978-03-18,Paris (Paris),80,Somme,2,...,25/09/2023 / 09/06/2024 / fin de législature,Cheffe de service socio-éducatif,464,https://www2.assemblee-nationale.fr/deputes/fi...,795774,ingrid-dordain,https://www.nosdeputes.fr/ingrid-dordain,https://www.nosdeputes.fr/ingrid-dordain/csv,0,NaN
614,605,Mereana Reid Arbelot,Reid Arbelot,Mereana,F,1970-09-12,Papeete (France),987,Polynésie Française,3,...,10/06/2023 / 09/06/2024 / fin de législature,ingénieur en chef du contrôle de la navigation...,582,https://www2.assemblee-nationale.fr/deputes/fi...,795240,mereana-reid-arbelot,https://www.nosdeputes.fr/mereana-reid-arbelot,https://www.nosdeputes.fr/mereana-reid-arbelot...,0,NaN
615,607,Philippe Emmanuel,Emmanuel,Philippe,H,1960-06-08,Versailles (Yvelines),78,Yvelines,10,...,21/08/2023 / 09/06/2024 / fin de législature,retraité,398,https://www2.assemblee-nationale.fr/deputes/fi...,795688,philippe-emmanuel,https://www.nosdeputes.fr/philippe-emmanuel,https://www.nosdeputes.fr/philippe-emmanuel/csv,0,Philemmanue
616,602,René Pilato,Pilato,René,H,1962-08-31,Lagny-sur Marne (Seine-et-Marne),16,Charente,1,...,29/01/2023 / 09/06/2024 / fin de législature,Enseignant,520,https://www2.assemblee-nationale.fr/deputes/fi...,817211,rene-pilato,https://www.nosdeputes.fr/rene-pilato,https://www.nosdeputes.fr/rene-pilato/csv,0,PilatoRene
617,618,Denis Bernaert,Bernaert,Denis,H,1964-05-01,Saint-Mandé (Val-de-Marne),78,Yvelines,4,...,12/02/2024 / 09/06/2024 / fin de législature,NaN,404,https://www2.assemblee-nationale.fr/deputes/fi...,795572,denis-bernaert,https://www.nosdeputes.fr/denis-bernaert,https://www.nosdeputes.fr/denis-bernaert/csv,0,DenisBernaert

In [ ]:
datas=[]
years=['07','12','17','22']
for i in years:
    str='deputes/deputes_20'+i+'.csv'
    df0=pd.read_csv(str,delimiter=';')[['nom','groupe_sigle','mandat_debut']]
    datas.append(df0)

Index(['nom', 'groupe_sigle', 'mandat_debut'], dtype='object')
Index(['nom', 'groupe_sigle', 'mandat_debut'], dtype='object')
Index(['nom', 'groupe_sigle', 'mandat_debut'], dtype='object')
Index(['nom', 'groupe_sigle', 'mandat_debut'], dtype='object')

In [42]:
df=pd.concat(datas)
good_years=['2007','2012','2017','2022']
df['mandat_debut']=df['mandat_debut'].apply(lambda x:x[:4])
df.dropna(inplace=True)
df=df[df['mandat_debut'].isin(good_years)]
df.drop(columns=['nom'],inplace=True)
df

    groupe_sigle mandat_debut
0            UMP         2007
1            UMP         2007
2            SRC         2007
3            UMP         2007
4            UMP         2007
..           ...          ...
600        MODEM         2022
601          REN         2022
602        MODEM         2022
603          HOR         2022
610        MODEM         2022

[2252 rows x 2 columns]

In [43]:
df['groupe_sigle'].unique()

array(['UMP', 'SRC', 'NI', 'GDR', 'NC', 'LR', 'SER', 'UDI', 'RRDP',
       'LREM', 'MODEM', 'SOC', 'NG', 'LT', 'AE', 'LFI', 'UAI', 'REN',
       'RN', 'ECO', 'HOR', 'LIOT'], dtype=object)

In [44]:
pairs=df.groupby(['groupe_sigle','mandat_debut']).size().reset_index(name='count')

In [50]:
pairs[pairs['mandat_debut']=='2022']

   groupe_sigle mandat_debut  count
1           ECO         2022     20
5           GDR         2022     22
6           HOR         2022     32
8           LFI         2022     75
9          LIOT         2022     21
12           LR         2022     60
14         LREM         2022      1
17        MODEM         2022     56
23           NI         2022      8
24          REN         2022    175
25           RN         2022     89
30          SOC         2022     30

In [47]:
pairs['groupe_sigle'].unique()

array(['AE', 'ECO', 'GDR', 'HOR', 'LFI', 'LIOT', 'LR', 'LREM', 'LT',
       'MODEM', 'NC', 'NG', 'NI', 'REN', 'RN', 'RRDP', 'SER', 'SOC',
       'SRC', 'UAI', 'UDI', 'UMP'], dtype=object)

In [ ]:
french_political_parties = {
    'AE': 'ALLIANCE ÉCOLOGISTE INDÉPENDANTE',
    'ECO': 'EUROPE ÉCOLOGIE LES VERTS',
    'GDR': 'DÉMOCRATIE ET RÉPUBLIQUE',
    'HOR': 'HORIZONS',
    'LFI': 'LA FRANCE INSOUMISE',
    'LIOT': 'LIBERTÉS, INDÉPENDANTS, OUTRE-MER ET TERRITOIRES',
    'LR': 'LES RÉPUBLICAINS',
    'LREM': 'LA RÉPUBLIQUE EN MARCHE',
    'LT': 'LIBERTÉ ET TERRITOIRES',
    'MODEM': 'MOUVEMENT DÉMOCRATE',
    'NC': 'NOUVEAU CENTRE',
    'NG': 'NOUVELLE GAUCHE',
    'NI': 'NON-INSCRITS',
    'REN': 'RENAISSANCE',
    'RN': 'RASSEMBLEMENT NATIONAL',
    'RRDP': 'RADICAL, RÉPUBLICAIN, DÉMOCRATE ET PROGRESSISTE',
    'SER': 'SOCIALISTES, ÉCOLOGISTES ET RÉPUBLICAINS',
    'SOC': 'PARTI SOCIALISTE',
    'SRC': 'SOCIALISTE, RADICAL, CITOYEN ET DIVERS GAUCHE',
    'UAI': 'UNION POUR LA DÉMOCRATIE FRANÇAISE',
    'UDI': 'UNION DES DÉMOCRATES ET INDÉPENDANTS',
    'UMP': 'UNION POUR UN MOUVEMENT POPULAIRE'
}

print(french_political_parties)